title: AliceLinux
subtitle: "AliceLinux's official documentation and dev blog"
baseURL: 'https://alicelinux.github.io'
languageCode: en-us
theme: hugo-werx
publishDir: 'pub'
enableRobotsTXT: true

ignoreFiles: ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames: true
enableEmoji: true
footnotereturnlinkcontents: "↩"

permalinks:
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: about
      name: About
      url: /about/
      weight: 2
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 3
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 4
  feed:
    - identifier: rss
      name: Subscribe
      url: /index.xml

taxonomies:
  category: categories
  series: series
  tag: tags

params:
  abbrDateFmt: "Jan 2"
  author: "Emmett1"
  brandIconFile: "images/icon.svg"
  dateFmt: "02.01.2006 15:04"
  ##
  ## Options for overriding theme or page defaults
  ##
  #customStylesheets: # Use to override theme styles, like logo size
  #  - "css/custom.css"
  #readingSpeed: 600 # Use to set custom reading speed
  #readingSpeedMin: 25 # Use to set custom reading speed range
  #readingSpeedMax: 175 # Use to set custom reading speed range
  social:
    - name: Codeberg
      url: 'https://codeberg.org/emmett1/alicelinux'
    - name: Github
      url: 'https://github.com/xplshn/alicelinux'
    - name: Telegram
      url: 'https://t.me/alicelinux'
    - name: Paypal
      url: 'https://paypal.me/syazwanemmett'
    - name: ko-fi
      url: 'https://ko-fi.com/emmett1'
    - name: buymeacoffee
      url: 'https://buymeacoffee.com/emmett1'

markup:
  goldmark:
    renderer:
      unsafe: true
