title = "AliceLinux"
subtitle = "AliceLinux's official documentation and dev blog"
baseURL = "https://xplshn.github.io/alicelinux"
languageCode = "en-us"
theme = "hugo-werx"
publishDir = "pub"
enableRobotsTXT = true

ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
enableEmoji = true
footnotereturnlinkcontents = "↩"

[[module.mounts]]
  source = 'assets'
  target = 'assets'

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
[[menu.feed]]
    name = "Subscribe"
    url = "/index.xml"

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[params]
    abbrDateFmt = "Jan 2"
    author = "Emmett1"
    brandIconFile = "assets/images/icon.svg"
    dateFmt = "02.01.2006 15:04"
    #customStylesheets = ["css/custom.css"]
    #readingSpeed = 600
    #readingSpeedMin = 25
    #readingSpeedMax = 175

[[social]]
    name = "Codeberg"
    url = "https://codeberg.org/emmett1/alicelinux"
[[social]]
    name = "Github"
    url = "https://github.com/xplshn/alicelinux"
[[social]]
    name = "Telegram"
    url = "https://t.me/alicelinux"
[[social]]
    name = "Paypal"
    url = "https://paypal.me/syazwanemmett"
[[social]]
    name = "ko-fi"
    url = "https://ko-fi.com/emmett1"
[[social]]
    name = "buymeacoffee"
    url = "https://buymeacoffee.com/emmett1"

[markup.goldmark.renderer]
hardWraps = false
unsafe = true

[markup.goldmark.renderHooks.image]
enableDefault = true
