name: Build latest src -> Release up-to-date rootfs
on:
  schedule:
    - cron: '0 0 */7 * *'  # Run every 7 days at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
      options: "--privileged"
    permissions:
      contents: write

    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: 'master'

    - name: Install dependencies
      run: |
        apk add --no-cache wget tar xz

    - name: Download stage rootfs -> update -> rebuild -> mkrootfs.sh 
      run: |
        mkdir /tmp/alicerootfs
        wget -qO- https://codeberg.org/emmett1/alicelinux/releases/download/20241006/alicelinux-rootfs-20241006.tar.xz | tar xJf - -C /tmp/alicerootfs
        cat <<'EOF' > /tmp/alicerootfs/usr/bin/__reconfigure
        #!/bin/sh -x
        mkdir -p /var/cache/src /var/cache/work /var/cache/pkg
        git clone --depth=1 https://codeberg.org/xplshn/alicelinux /var/lib/alicelinux

        cat <<'APKG_CONF' > /etc/apkg.conf
        # apkg configuration file
        export CFLAGS="-O2 -pipe"
        export CXXFLAGS="$CFLAGS"
        export MAKEFLAGS="-j$(nproc)"
        export NINJAJOBS="$(nproc)"
        APKG_REPO="/var/lib/alicelinux/repos/core /var/lib/alicelinux/repos/extra /var/lib/alicelinux/repos/wayland"
        APKG_PACKAGE_DIR="/var/cache/pkg"
        APKG_SOURCE_DIR="/var/cache/src"
        APKG_WORK_DIR="/var/cache/work"
        export keep_static=1
        APKG_CONF
        apkg -s clang && echo "Repos are working"
        export SPM_FORCEINSTALL=1 APKG_NOPROMPT=1
        apkg -U
        apkg -t
        EOF

        chmod +x /tmp/alicerootfs/usr/bin/__reconfigure
        /tmp/alicerootfs/usr/bin/apkg-chroot /tmp/alicerootfs __reconfigure
        echo "Trying to prepare a rootfs with mkrootfs.sh"
        /tmp/alicerootfs/usr/bin/apkg-chroot ./tmp/alicerootfs __mkrootfs.sh

    - name: Create Release
      uses: softprops/action-gh-release@v2.2.1
      with:
        name: "Latest Build"
        tag_name: "release-${{ github.run_number }}"
        prerelease: false
        draft: false
        generate_release_notes: true
        make_latest: true
        files: |
          ./rootfs.tar.xz
          ./alicelinux-rootfs-$(date +%Y%m%d).tar.xz
          ./alicelinux-rootfs-$(date +%Y%m%d).tar.xz.pkglist
          ./alicelinux-rootfs-$(date +%Y%m%d).tar.xz.sha256sum
      continue-on-error: true

# I like nonsense; it wakes up the brain cells
