name: Deploy static content to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    container:
      image: alpine:latest

    steps:
      - name: Install dependencies
        run: |
          apk update
          apk add hugo git tar

      - name: Checkout GitHub repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags
          ref: 'master'  # Checkout the master branch

      - name: Generate the site
        run: |
          # Navigate to the ./www directory and generate site content
          cd ./www
          sh ./gen.sh
          cd ..

          # Prepare git to commit changes in ./www
          git config user.name '󰬭 [CI] '
          git config user.email 'action@github.com'

          # Commit changes in ./www
          git add www
          git commit -m "[www]" || echo "Nothing to commit"
          git push origin HEAD || echo "Push failed; check repository settings"

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './www/public'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
