name: Deploy static content to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    container:
      image: alpine:latest

    steps:
      - name: Install dependencies
        run: |
          apk update
          apk add hugo git tar

      - name: Checkout GitHub repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags
          ref: 'master'  # Checkout the master branch

      - name: Configure Git safe.directory
        run: |
          git config --global --add safe.directory "${GITHUB_WORKSPACE}"

      - name: Generate the site
        run: |
          # Use dynamic paths based on GITHUB_WORKSPACE
          GEN_DIR="${GITHUB_WORKSPACE}/www"
          PUBLIC_DIR="${GEN_DIR}/public"

          # Navigate to the generation directory and run the script
          cd "${GEN_DIR}"
          sh ./gen.sh
          cd "${GITHUB_WORKSPACE}"

          # Prepare git to commit changes
          git config user.name '[CI]'
          git config user.email 'action@github.com'

          # Commit changes dynamically
          git add "${GEN_DIR}"
          git commit -m "[www]" || echo "Nothing to commit"
          git push origin HEAD || echo "Push failed; check repository settings"

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "${GITHUB_WORKSPACE}/www/public"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
