name: Sync with Codeberg
on:
  schedule:
    - cron: '0 0 */3 * *'  # Run every 3 days at midnight
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: 'master'
    - name: Add Codeberg remote
      run: |
        git remote add codeberg https://codeberg.org/emmett1/alicelinux.git
    - name: Fetch changes from Codeberg
      run: |
        git fetch codeberg
    - name: Checkout master
      run: |
        git checkout master
    - name: Fetch changes in submodules
      run: |
        git submodule update --recursive --remote
    - name: Merge changes
      run: |
        git config user.name '󰬭 [CI] '
        git config user.email 'action@github.com'
        git merge --allow-unrelated-histories codeberg/clang
    - name: Commit and push changes to GitHub
      run: |
        git add .
        git commit -m "Sync" || true
        git push origin master || true
