name: Sync with Codeberg

on:
  schedule:
    - cron: '0 0 */3 * *'  # Run every 3 days at midnight
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: 'master'

    - name: Add Codeberg remote
      run: |
        git remote add codeberg https://codeberg.org/emmett1/alicelinux.git

    - name: Fetch changes from Codeberg
      run: |
        git fetch codeberg

    - name: Checkout Codeberg pages branch
      run: |
        git checkout -b codeberg-pages codeberg/pages

    - name: Copy docs folder from pages branch
      run: |
        rm -f ./docs/*.html
        cp -r docs ../docs-temp
        git checkout clang
        rm -rf docs
        mv ../docs-temp docs

    - name: Fetch changes in submodules
      run: |
        git submodule update --recursive --remote

    - name: Merge changes
      run: |
        git config user.name '󰬭 [CI] '
        git config user.email 'action@github.com'
        git merge --allow-unrelated-histories codeberg/main

    - name: Commit and push changes to GitHub
      run: |
        git add .
        git commit -m "Sync" || true
        git push origin master || true
